name: "Normalize branch name"
description: "Normalizes the branch into an "
inputs:
  branch:
    description: "Branch name to normalize. Defaults to $GITHUB_HEAD_REF"
    required: false
  max_length:
    description: "Max length of the branch name. If exceeds, string will be striped down to first max_length chars. Defaults to 40 chars"
    required: false
outputs:
  normalized:
    description: "Normalized branch name"
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: 'terminal'
  color: 'green'